### ISSUE TITLE
Implementation of JAXB-API has not been found on module path or classpath.

### ISSUE THREAD

**Issue by janbman4** [spring-guides/gs-producing-web-service#37]
When I start the application from the 'complete' directory and call the SOAP endpoint, I receice the following error message:
`Implementation of JAXB-API has not been found on module path or classpath.`
What's going wrong?

**Comment by clebermacieski** [comment]
Adding this dependecies solve the problem th the pom.xml...

`		<dependency>
			<groupId>javax.xml.bind</groupId>
			<artifactId>jaxb-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.glassfish.jaxb</groupId>
			<artifactId>jaxb-runtime</artifactId>
			<scope>runtime</scope>
              </dependency>`

**Comment by MathiasDeWeerdt** [comment]
This should be added to the "from scratch" documentation.

**Comment by mrmamadi** [comment]
Adding the jaxb dependency, `implementation 'org.glassfish.jaxb:jaxb-runtime:2.3.2'` to the `build.gradle` file in the 'complete' directory seems to have fixed it for me.

**Comment by maozheng233** [comment]
> Adding this dependecies to the pom.xml solve the problem...
> 
> ` <dependency> <groupId>javax.xml.bind</groupId> <artifactId>jaxb-api</artifactId> </dependency> <dependency> <groupId>org.glassfish.jaxb</groupId> <artifactId>jaxb-runtime</artifactId> <scope>runtime</scope> </dependency>`

I dont know why it works...but it is a right way

**Comment by pengzj** [comment]
> 

Thank you. Unfortunately it doesn't work with gradle

	implementation 'org.springframework.boot:spring-boot-starter-web-services'
	implementation 'wsdl4j:wsdl4j'
	jaxb("org.glassfish.jaxb:jaxb-xjc")


	implementation 'javax.xml.bind:jaxb-api:2.3.1'
	implementation 'org.glassfish.jaxb:jaxb-runtime:4.0.0'

**Comment by pengzj** [comment]
I resolved this issue by downgrade the version of jaxb-runtime.

    implementation 'wsdl4j:wsdl4j'
    jaxb("org.glassfish.jaxb:jaxb-xjc")
    implementation 'org.glassfish.jaxb:jaxb-runtime:2.3.6'
[build.gradle.txt](https://github.com/spring-guides/gs-producing-web-service/files/9603473/build.gradle.txt)



The whole gralde file is:

**Comment by pengzj** [comment]
Here is one better answer to the question
https://stackoverflow.com/questions/72390822/java-lang-classnotfoundexception-com-sun-xml-bind-v2-contextfactory

**Comment by huima** [comment]
This is solved easily by adding dependency:

	// For Java 11:
	implementation 'org.glassfish.jaxb:jaxb-runtime'

This was already done and used on the consuming side project.

**Comment by najjariheb6** [comment]
You just need to add this to pom.xml : 
`<outputDirectory>${project.basedir}/src/main/java</outputDirectory>`
`<clearOutputDir>false</clearOutputDir>`
because that dependency (jaxb-api & jaxb-runtime) get the classes from target folder, and when we add those config lines, the classes will be added to the main folder and be visible to the project and won't shows error any more.
So it will be like this :
`<plugin>`
`<groupId>org.codehaus.mojo</groupId>`
`<artifactId>jaxb2-maven-plugin</artifactId>`
`<version>3.1.0</version>`
`<executions><execution><id>xjc</id><goals><goal>xjc</goal></goals></execution></executions>`
`<configuration>`
`<sources><source>${project.basedir}/src/main/resources/countries.xsd</source></sources>`
`<outputDirectory>${project.basedir}/src/main/java</outputDirectory>`
`<clearOutputDir>false</clearOutputDir>`
`</configuration>`
`</plugin>`
